name: demos
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  angular2: ^2.0.0
  angular2_components:
  args: '^0.13.4+2'
  archive: '^1.0.24'
  browser: '^0.10.0'
  chartjs: '^0.3.0'
  crypto: '^2.0.1'
  #cryptoutils: '0.2.1'
  dama:
    git:
      url: git://github.com/thumbert/dama.git
  dart_to_js_script_rewriter: ^1.0.1
  date:
    git:
      url: git://github.com/thumbert/date.git
  dygraphs_dart:
      git:
        url: git://github.com/thumbert/dygraphs_dart.git
  intl: ">=0.14.0 <0.15.0"
  google_charts: '^0.2.1'
  http: '0.11.3+9'
  js: '^0.6.0'
  #lightning: '^2.1.3'
  mongo_dart: "^0.2.7"
  more: '^1.5.1'
  petitparser: ">=1.0.0 <2.0.0"
  quiver: '>=0.22.0 <0.24.0'
  stagexl: '^0.13.12'
  spreadsheet_decoder: '^0.3.1'
  timezone: "^0.4.3"

dev_dependencies:
  test: '>=0.12.13 <0.13.0'

#transformers:
#- angular2:
#    platform_directives:
#    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
#    platform_pipes:
#    - 'package:angular2/common.dart#COMMON_PIPES'
#    entry_points: web/main.dart
#- dart_to_js_script_rewriter