name: demos
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  csv: ^5.0.0
  date:
    git: https://github.com/thumbert/date.git
  dama:
    git: https://github.com/thumbert/dama.git
  elec_server:
    git: https://github.com/thumbert/elec-server.git
  intl: ^0.17.0
  mongo_dart: ^0.7.0+1
  quiver: ^3.0.1
  table:
    git: https://github.com/thumbert/table.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: ^0.8.0
  trotter: ^2.0.0
  tuple: ^2.0.0
  xml: ^6.1.0

  #  args: '>=1.5.0 <2.0.0'
#  archive: '>=2.0.0 <3.0.0'
#  browser: '^0.10.0'
#  crypto: '^2.0.1'
#  csv: '>=4.0.0 <5.0.0'
  #cryptoutils: '0.2.1'
#  dama:
#    git:
#      url: git://github.com/thumbert/dama.git
#  dart_to_js_script_rewriter: ^1.0.1
#  date:
#    git:
#      url: git://github.com/thumbert/date.git
#  dygraphs_dart:
#      git:
#        url: git://github.com/thumbert/dygraphs_dart.git
#  elec:
#        git:
#          url: git://github.com/thumbert/elec.git
#  elec_server:
#        git:
#          url: git://github.com/thumbert/elec-server.git
#  petitparser: '>=3.0.4 <4.0.0'
#  plotly:
#    git:
#      url: git://github.com/thumbert/plotly.git
#  quiver: '>=2.0.0 <3.0.0'
#  stagexl: 1.4.0+2
#  spreadsheet_decoder: '^0.3.1'
#  timezone: '>=0.5.5 <1.0.0'
#  table:
#    git:
#      url: git://github.com/thumbert/table.git
#  timeseries:
#    git:
#      url: git://github.com/thumbert/timeseries.git
#  tuple: '^1.0.2'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.4
