name: demos
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: any
  archive: any
  browser: '>=0.9.0 <0.10.0'
  charted: any
  crypto: any
  csv: any
  html5lib: any
  intl: ">=0.12.0+3 <0.13.0"
  mongo_dart: any
  more: any
  polymer: any
  polymer_elements: any
  polymer_expressions: any
  polymer_ui_elements: any
  stagexl: any
  timezone: any
  unittest: any
