name: demos
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  args: '>=1.5.0 <2.0.0'
  archive: '>=2.0.0 <3.0.0'
#  browser: '^0.10.0'
#  crypto: '^2.0.1'
  csv: '>=4.0.0 <5.0.0'
  #cryptoutils: '0.2.1'
  dama:
    git:
      url: git://github.com/thumbert/dama.git
#  dart_to_js_script_rewriter: ^1.0.1
  date:
    git:
      url: git://github.com/thumbert/date.git
#  dygraphs_dart:
#      git:
#        url: git://github.com/thumbert/dygraphs_dart.git
  elec:
        git:
          url: git://github.com/thumbert/elec.git
  elec_server:
        git:
          url: git://github.com/thumbert/elec-server.git
  grpc: '>=1.0.0 <2.0.0'
  html: 0.13.3+3
  http: '>=0.12.0 <0.13.0'
  intl: ">=0.15.7 <0.16.0"
  js: '>=0.6.0 <0.7.0'
  mongo_dart: ^0.4.0
  more: '>=1.12.0 <2.0.0'
  petitparser: '>=2.0.0 <3.0.0'
  plotly:
    git:
      url: git://github.com/thumbert/plotly.git
  quiver: '>=2.0.0 <3.0.0'
  stagexl: 1.4.0+2
#  spreadsheet_decoder: '^0.3.1'
  timezone: '>=0.5.5 <1.0.0'
  table:
    git:
      url: git://github.com/thumbert/table.git
  timeseries:
    git:
      url: git://github.com/thumbert/timeseries.git
  trotter: '>=1.0.0 <2.0.0'
  tuple: '^1.0.2'

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
  test: '>=1.0.0 <2.0.0'
