name: demos
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: any
  archive: any
  browser: any
  charted: any
  crypto: any
  csv: any
  html5lib: any
  intl: ">=0.1.0 <0.13.0"
  mongo_dart: any
  more: any
  petitparser: ">=1.0.0 <2.0.0"
  intl: any
  stagexl: any
  test: ">=0.12.0 <0.13.0"
  timezone: any
  unittest: "<0.13.0"