name: demos
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: any
  archive: any
  browser: any
  charted: any
  crypto: any
  csv: any
  date:
    git:
      url: git://github.com/thumbert/date.git
      ref: '0.0.3'
  either: "<= 0.1.8"
  intl: ">=0.1.0 <0.13.0"
  mongo_dart: "^0.2.4"
  more: '^1.5.0'
  petitparser: ">=1.0.0 <2.0.0"
  intl: any
  stagexl: '^0.13.0'
  timezone: "^0.3.1"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'