name: demos
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  args: '>=1.5.0 <2.0.0'
  archive: '>=2.0.0 <3.0.0'
#  browser: '^0.10.0'
#  crypto: '^2.0.1'
  csv: '>=4.0.0 <5.0.0'
  #cryptoutils: '0.2.1'
  dama:
    git:
      url: git://github.com/thumbert/dama.git
#  dart_to_js_script_rewriter: ^1.0.1
  date:
    git:
      url: git://github.com/thumbert/date.git
#  dygraphs_dart:
#      git:
#        url: git://github.com/thumbert/dygraphs_dart.git
  elec:
        git:
          url: git://github.com/thumbert/elec.git
  elec_server:
        git:
          url: git://github.com/thumbert/elec-server.git
  intl: ">=0.15.7 <0.16.0"
  html: 0.13.3+3
  http: '>=0.11.1 <0.13.0'
  js: '>=0.6.0 <0.7.0'
  mongo_dart: ^0.3.3
  more: '>=1.12.0 <2.0.0'
  petitparser: '>=2.0.0 <3.0.0'
#  plotly: 0.7.3
#  quiver: '>=0.22.0 <0.24.0'
#  stagexl: 1.2.0+3
#  spreadsheet_decoder: '^0.3.1'
  timezone: "^0.5.0-dev-3"
  table:
    git:
      url: git://github.com/thumbert/table.git
  trotter: '>=1.0.0 <2.0.0'
  tuple: '^1.0.2'

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
