name: demos
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  archive: any
  browser: '>=0.9.0 <0.10.0'
  html5lib: any
  intl: any
  mongo_dart: any
  polymer: any
  polymer_elements: any
  polymer_expressions: any
  polymer_ui_elements: any
  unittest: any
