name: plotly_examples
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: thumbert <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  plotly:
    git:
      url: git://github.com/thumbert/plotly.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.0.0

