name: dartice
version: 0.0.1
author: Tony Humbert
description: A Dart lattice  look alike
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  charted: any
  stagexl: any
dev_dependencies:
  unittest: any
