name: timeseries
version: 0.0.1
author: Tony Humbert
description: timeseries functionality for Dart
dependencies:
  intl: any
  logging: any
  logging_handlers: any
  timezone: ">=0.2.5"
  unittest: any
