name: cviewer
version: 0.0.1
description: A minimal command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: any
  mongo_dart: any
  petitparser: '>=1.0.0 <2.0.0'
  stagexl: any
dev_dependencies:
  unittest: any
