name: trex
description: Trex application
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  polymer: '>=0.12.0 <0.13.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    - test/demo_app_test.html
